apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases
  - namespace.yaml

namespace: nginx-dev

commonLabels:
  environment: dev

patches:
  - path: deployment.yaml
