apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases
  - namespace.yaml

namespace: ns-dev

commonLabels:
  environment: dev

patches:
  - target:
      kind: Deployment
      name: web-app-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: httpd:latest
  - target:
      kind: Ingress
      name: web-app-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.techdemos.site
