apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases
  - namespace.yaml
  - ingress.yaml

namespace: nginx-prod

commonLabels:
  environment: prod

patches:
  - path: deployment.yaml
