apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases
  - namespace.yaml

namespace: demo-prod

commonLabels:
  environment: prod

patches:
  - target:
      kind: Deployment
      name: demo-deployment
    path: deployment-patch.json
  - target:
      kind: Ingress
      name: demo-ingress
    path: ingress-patch.json
